repository_type: pipeline
lint:
  files_exist:
    - CODE_OF_CONDUCT.md
    - assets/nf-core-variantinterpretation_logo_light.png
    - docs/images/nf-core-variantinterpretation_logo_light.png
    - docs/images/nf-core-variantinterpretation_logo_dark.png
  nextflow_config:
    - manifest.name
    - manifest.homePage
  multiqc_config:
    - report_comment
nf_core_version: "2.14.1"
